name: graphql_ppx pipeline

on: [push, pull_request]

jobs:
  test_and_build_linux:
    name: ${{ matrix.os }}/node-${{ matrix.node-version }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        node-version: [12.x]
        os: [ubuntu-latest]

    container:
      # https://github.com/baransu/docker-esy
      image: cichocinski/docker-esy:alpine3.8

    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Get esy store path
        id: esy_cache_path
        shell: bash
        run: |
          # COMPUTE THE ESY INSTALL CACHE LOCATION AHEAD OF TIME
          DESIRED_LEN="86"
          HOME_ESY3="$HOME/.esy/3"
          HOME_ESY3_LEN=${#HOME_ESY3}
          NUM_UNDERS=$(echo "$(($DESIRED_LEN-$HOME_ESY3_LEN))")
          UNDERS=$(printf "%-${NUM_UNDERS}s" "_")
          UNDERS="${UNDERS// /_}"
          THE_ESY__CACHE_INSTALL_PATH=${HOME_ESY3}${UNDERS}/i
          echo "THE_ESY__CACHE_INSTALL_PATH: $THE_ESY__CACHE_INSTALL_PATH"
          echo "##[set-output name=path;]$THE_ESY__CACHE_INSTALL_PATH"
      - name: Restore esy cache
        uses: actions/cache@v1
        with:
          path: ${{ steps.esy_cache_path.outputs.path }}
          key: v1-esy-${{ matrix.os }}-${{ hashFiles('**/index.json') }}
          restore-keys: |
            v1-esy-${{ matrix.os }}-

      - name: Add python
        run: |
          apk add python
      # Ocaml 4.08+
      - name: install-build
        run: |
          esy install
      - name: test-native
        run: |
          esy b dune runtest -f

      # OCaml 4.06 and BuckleScript 6
      - name: install-build @406
        run: |
          esy @406 install
          esy @406 b
      - name: test-bsb6
        working-directory: ./tests_bucklescript
        run: |
          npm install --no-optional
          npm test
        env:
          CI: true
      - name: install-build @406 (static release)
        run: |
          esy @406 dune build --root . --only-packages '#{self.name}' --ignore-promoted-rules --no-config --profile release-static
      - name: (only on release) Upload artifacts ${{ matrix.os }}
        if: github.event_name != 'pull_request' && startsWith(github.ref, 'refs/tags/')
        uses: actions/upload-artifact@master
        with:
          name: ${{ matrix.os }}-bsb6
          path: _build/default/src/bucklescript_bin/bin.exe

  test_and_build:
    name: ${{ matrix.os }}/node-${{ matrix.node-version }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        node-version: [12.x]
        os: [windows-latest, macOS-latest]

    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install esy
        run: |
          npm install -g esy@0.6.0

      - name: Get esy store path
        id: esy_cache_path
        shell: bash
        run: |
          # COMPUTE THE ESY INSTALL CACHE LOCATION AHEAD OF TIME
          if [ "${{ matrix.os }}" == "windows-latest" ]; then
            THE_ESY__CACHE_INSTALL_PATH=$HOME/.esy/3_/i
            THE_ESY__CACHE_INSTALL_PATH=$( cygpath --mixed --absolute "$THE_ESY__CACHE_INSTALL_PATH")
          else
            DESIRED_LEN="86"
            HOME_ESY3="$HOME/.esy/3"
            HOME_ESY3_LEN=${#HOME_ESY3}
            NUM_UNDERS=$(echo "$(($DESIRED_LEN-$HOME_ESY3_LEN))")
            UNDERS=$(printf "%-${NUM_UNDERS}s" "_")
            UNDERS="${UNDERS// /_}"
            THE_ESY__CACHE_INSTALL_PATH=${HOME_ESY3}${UNDERS}/i
          fi
          echo "THE_ESY__CACHE_INSTALL_PATH: $THE_ESY__CACHE_INSTALL_PATH"
          echo "##[set-output name=path;]$THE_ESY__CACHE_INSTALL_PATH"
      - name: Restore esy cache
        uses: actions/cache@v1.1.0
        with:
          path: ${{ steps.esy_cache_path.outputs.path }}
          key: v1-esy-${{ matrix.os }}-${{ hashFiles('**/index.json') }}
          restore-keys: |
            v1-esy-${{ matrix.os }}-

      # Ocaml 4.08+
      - name: install-build
        run: |
          esy install
      - name: test-native
        run: |
          esy b dune runtest -f

      # OCaml 4.06 and BuckleScript 6
      - name: install-build
        run: |
          esy @406 install
          esy @406 b
      # - name: test-bsb6
      #   working-directory: ./tests_bucklescript
      #   run: |
      #     npm install --no-optional
      #     npm test
      - name: (only on release) Upload artifacts ${{ matrix.os }}
        if: github.event_name != 'pull_request' && startsWith(github.ref, 'refs/tags/')
        uses: actions/upload-artifact@master
        with:
          name: ${{ matrix.os }}-bsb6
          path: _build/default/src/bucklescript_bin/bin.exe

  publish:
    needs: test_and_build
    if: github.event_name != 'pull_request' && startsWith(github.ref, 'refs/tags/')
    name: (only on release) Publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: "12.x"
          registry-url: "https://registry.npmjs.org"

      - name: Download bsb6 linux artifacts
        if: success()
        uses: actions/download-artifact@master
        with:
          name: ubuntu-latest-bsb6
          path: binaries/linux

      - name: Download bsb6 macOS artifacts
        if: success()
        uses: actions/download-artifact@master
        with:
          name: macOS-latest-bsb6
          path: binaries/darwin

      - name: Download bsb6 windows artifacts
        if: success()
        uses: actions/download-artifact@master
        with:
          name: windows-latest-bsb6
          path: binaries/windows

      - name: Move bsb artifacts
        if: success()
        run: |
          mkdir -p bin/bsb6
          mv binaries/darwin/bin.exe bin/bsb6/graphql_ppx-darwin-x64.exe
          mv binaries/windows/bin.exe bin/bsb6/graphql_ppx-win-x64.exe
          mv binaries/linux/bin.exe bin/bsb6/graphql_ppx-linux-x64.exe

      - name: Publish
        if: success()
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
